### ISSUE TITLE
Conflict

### ISSUE THREAD

**Issue by behoof** [bozoh/moodle-mod_simplecertificate#180]
Using the plugin Fitlercodes (https://moodle.org/plugins/filter_filtercodes):

The {username} in your certificate is not anymore the first name and last name, which gives the worng output. 

Could you adjust this in the simple certificate plugin?

Best regards,

Bert

**Comment by bozoh** [comment]
Well  ,  i can't  reproduce this error,  username  still output full username ,  and look at the code from branches Master-> Moodle 3.0 (2.2.6 versions)  it's  still  users full username  in USERNAME.
Check your code please.
And i don't know nothing about  filter_filtercodes 


MOODLE 3.3
https://github.com/bozoh/moodle-mod_simplecertificate/blob/MOODLE_33/locallib.php#L1329

MOODLE 3.2
https://github.com/bozoh/moodle-mod_simplecertificate/blob/MOODLE_32/locallib.php#L1351

MOODLE 3.1
https://github.com/bozoh/moodle-mod_simplecertificate/blob/MOODLE_31/locallib.php#L1351

MOODLE 3.0
https://github.com/bozoh/moodle-mod_simplecertificate/blob/MOODLE_30/locallib.php#L1351

master branch
https://github.com/bozoh/moodle-mod_simplecertificate/blob/master/locallib.php#L1331

**Comment by bozoh** [comment]
Humm,  now i understand,  this plugins uses same textmarks them mine, but my pluging is  far more older them filtercodes plugin.
So if i change this textmark  will brake all user which have installed it before and uses this  textmark (all certificate uses this textmark for sure)
It's easier the filter_filtercodes changes the way he create the textmarks like [USERNAME] or [[USERNAME]]  or {{USERNAME}}  anything,  since my plungins is older and used by more the 2k sites, and this is newer and only used by 31 sites (in plungins stats page)

**Comment by bozoh** [comment]
After talk to filtercodes authors,  i will try to not use format_string function, this function apply filters on  text,  and i don't need it,  ai can use strip_tags, or something like that

https://github.com/michael-milette/moodle-filter_filtercodes/issues/8
