### ISSUE TITLE
Incorrect Date when generate certificate as "logged in user"

### ISSUE THREAD

**Issue by matthewvryan** [bozoh/moodle-mod_simplecertificate#201]
**Describe the bug**
The date that appears on the certificate when "logged in as the user" is today's date, rather than the completion date or issued date of the certificate.

**Moodle Version(s)**
The moodle version Moodle 3.2.9
Simple Certificate version 2.2.7 2017120400

**To Reproduce**
1. Log in as Admin
2. Find a user and Login as that user
3. Navigate to a completed course
4. Navigate to the Certificate Activity
5. Generate Certificate

**Expected behavior**
The certificate is generated with either the Issue Date OR Completion Date, whichever has been set in SimplerCertificate Settings.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by bozoh** [comment]
This is outside of plugins user behavior. There is no reason for anyone to issue certificates in that way.

**Comment by luisdev** [comment]
> 
> 
> This is outside of plugins user behavior. There is no reason for anyone to issue certificates in that way.

If "There is no reason for anyone to issue certificates in that way" then the plugin should not allow any user to access the certificate "in that way". The fact that a user is able to generate a certificate this way using the "logged in as" feature and that the certificate is subsequently generated - with incorrect data - means that this is a problem. So I think this issue should be reopened.

What do you do if somebody DOES issue a certificate this way and then the certificate is distributed (with the incorrect date)? That will just make people question the integrity of the data.

If users should not issue certificates this way then users should be _prohibited_ from accessing the certificate this way.

Please reopen this issue so that it can be correctly fixed.

**Comment by bozoh** [comment]
_If users should not issue certificates this way then users should be prohibited from accessing the certificate this way._  
It is impossible to  know all the "creative" ways  a user uses to issue a certificate, and  "Logins as"  is a moodle functionality  and there is no easy ways to block it. 

_What do you do if somebody DOES issue a certificate this way and then the certificate is distributed (with the incorrect date)? That will just make people question the integrity of the data._
If you use a thing in a unexpected way,  you could have a unexpected results 

I don't understand  why an Admin will use "login as "  to issue a certificate to a user, since Bulk operations already do that
